version = '0.5.5'

[bindings]
"ctrl+c" = 'exit'
"?" = 'help'
j = 'down(1)'
k = 'up(1)'
down = 'down(1)'
up = 'up(1)'
left = 'lower_volume(1)'
right = 'raise_volume(1)'
h = [
    'left',
    'lower_volume(5)',
]
l = [
    'right',
    'raise_volume(5)',
]
"shift+h" = 'lower_volume(15)'
"shift+l" = 'raise_volume(15)'
scroll_down = 'lower_volume(5)'
scroll_up = 'raise_volume(5)'
m = 'mute'
mouse_middle = 'mute'
mouse_right = 'mute'
1 = 'show_output'
2 = 'show_input'
3 = 'show_cards'
F1 = 'show_output'
F2 = 'show_input'
F3 = 'show_cards'
tab = 'cycle_pages_forward'
"shift+tab" = 'cycle_pages_backward'
enter = [
    'context_menu',
    'confirm',
]
esc = 'close_context_menu'
q = [
    'exit',
    'close_context_menu',
]
[colors.normal]
fg = 'white'

[colors.bold]
fg = 'white'
attributes = ['bold']

[colors.inverted]
fg = 'black'
bg = 'white'

[colors.muted]
fg = 'grey'

[colors.red]
fg = 'red'

[colors.orange]
fg = 'yellow'

[colors.green]
fg = 'green'
